import '../globals.css'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import Topbar from "@/components/shared/Topbar"
import Footer from '@/components/shared/Footer'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Rails',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${montserrat.className}`} >
      <Topbar/>
      {children}
      <Footer/>
      </body>
    </html>
  )
}
